# -*- coding: utf-8 -*-
"""Python_Automation_Loops_SubjectiveQ1_PhanindraKumar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWEI6Sdkj4649SBPes6gkadT-TLYz2uM

**Task**: Movie Theatre Booking System
"""

"""Author: Phanindra Kumar Alahari"""

Max_seating_capt=350
Criteria_for_age=12
Max_booking_ticket=15
seat_count=0
Booking_count=0
Rejected_count=0
while(True):
  ticket_cnt=int(input("Enter Number of tickets going to book: "))
  if(Max_seating_capt-seat_count>=ticket_cnt and ticket_cnt > 0):
    if(Max_booking_ticket-ticket_cnt>=0):
      age_vaild_var=0
      for itr_var in range(ticket_cnt):
        age_value=int(input(f"Enter the age of the {itr_var+1} person:"))
        if age_value>=Criteria_for_age:
          age_vaild_var+=1
      if age_vaild_var == ticket_cnt:
        seat_count+=ticket_cnt
        Booking_count+=1
        print(f"Output: BOOKING CONFIRMED - {ticket_cnt} tickets ")
      else:
        Rejected_count+=1
        print(f"BOOKING REJECTED - Age restriction equal to OR greater than {Criteria_for_age}")
        continue
    else:
      print(f"Maximum allowed ticket booking is {Max_booking_ticket}. Which is greater than it {ticket_cnt}")
  elif ticket_cnt <0:
    print(f"Provide the number of tickets to book more >=0")
    continue
  else:
    print(f"Final Report: Total Bookings: {Booking_count}, Total Tickets Sold: {seat_count}, Rejected Bookings: {Rejected_count}, Remaining Seats: {Max_seating_capt-seat_count}")
    break

