# -*- coding: utf-8 -*-
"""python_basics_PhanindraKumar_Alahari.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeMuntGu6QNwC0qYgHtRCv9MeASpsK-Y

Task 1: Variables and Data Types
"""

name="Phani"
age=30
height=5.66
is_student=True
print(name,type(name))
print(age,type(age))
print(height,type(height))
print(is_student,type(is_student))

"""Task 2: String Formatting"""

print("Name: ",name," | Age: ",age," | Height: ",height," | Student: ",is_student)
print(f"Name:  {name} | Age:   {age} | Height:  {height}  | Student:  {is_student}")

"""Task 3: Arithmetic Operations"""

print(f"Age in months\t:\t{age*12}")
print(f"Age in days\t:\t{age*365}")
print(f"The remainder when age is divided by 7\t:\t{age%7}")
print(f"Age raised to the power of 2\t:\t{age**2}")