# -*- coding: utf-8 -*-
"""Python_Data Collections_Subjective_phanindrakumar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVsaiA7dyv4Paqz2NrAc3EsW7iCGs-Ho

Python: Organizing with Functions; Python: Data Collections - Subjective
:: Junior data analyst automating simple number-based reports using Python. Your manager wants all outputs generated using for loops only.

TASK1 : Write a for loop that prints all numbers from 1 to 5 using range()
"""

print('Printing all numbers from 1 to 5')
for i in range(1,6):
  print(f"{i}")

"""TASK 2: Write a for loop that prints only odd numbers between 1 and 10 using the step parameter in range()."""

print('Print only odd numbers between 1 and 10 using the step parameter in range().')
for i in range(1,10,2):
  print(f'{i}')

"""TASK 3: Write a nested for loop that prints the following pattern:

"""

for i in range(3):
  for j in range(2):
    print(f'{i} {j}')

"""TASK 4: Write a for loop that prints numbers from 1 to 7. If the number is 5, stop the loop immediately using break."""

for i in range(1,8):
  if i == 5:
    break
  print(i)